### ISSUE TITLE
use css variables for the colours

### ISSUE THREAD

**Issue by CodeMyst** [CodeMyst/myst.rs#12]

**Comment by harshhhdev** [comment]
Would you mind a few hardcoded colours? 
![image](https://user-images.githubusercontent.com/69592270/99863452-40e2cd80-2b6c-11eb-9a72-25aa5176c909.png)
For example the donate button. No need to make a seperate var for it, in my opinion.

**Comment by harshhhdev** [comment]
#13 has some vars for the colors :+1:
